In [2]:
import math
import numpy as np
import pandas as pd 

#### 1a)

In [38]:
def findOrderOfZ(p):
    columnsNumbers = [x for x in range(1,p)]
    rowNumbers = [x for x in range(2,p)]
    board = np.zeros((p-2,p-1))
    
    orders = []
    orders.append((1,1))
    for row in range(2,p):
        foundLowest = False
        for col in range(1,p):
            temp = (row**col)%p
            board[row-2][col-1] = temp
            if((temp == 1) and (foundLowest == False)): 
                orders.append((row, col))
                foundLowest = True
                
    return (board, orders)

z = 11
board, orders = findOrderOfZ(z)
print("Ordene i z{} er:".format(z))
print(orders)
print("\nBrettet ser slik ut:")
print(board)
    

Ordene i z11 er:
[(1, 1), (2, 10), (3, 5), (4, 5), (5, 5), (6, 10), (7, 10), (8, 10), (9, 5), (10, 2)]

Brettet ser slik ut:
[[ 2.  4.  8.  5. 10.  9.  7.  3.  6.  1.]
 [ 3.  9.  5.  4.  1.  3.  9.  5.  4.  1.]
 [ 4.  5.  9.  3.  1.  4.  5.  9.  3.  1.]
 [ 5.  3.  4.  9.  1.  5.  3.  4.  9.  1.]
 [ 6.  3.  7.  9. 10.  5.  8.  4.  2.  1.]
 [ 7.  5.  2.  3. 10.  4.  6.  9.  8.  1.]
 [ 8.  9.  6.  4. 10.  3.  2.  5.  7.  1.]
 [ 9.  4.  3.  5.  1.  9.  4.  3.  5.  1.]
 [10.  1. 10.  1. 10.  1. 10.  1. 10.  1.]]


#### 1b)

In [94]:
def LogaritmerAvZ(matrix):
    out = matrix
    a = 2
    b = 1
    for i, row in enumerate(matrix): 
        for j, col in enumerate(row):
            res = LogModular(a, b, len(row)+1)
            if(res):
                out[i][j] = res
            else:
                out[i][j] = '-1'
            b += 1
        a += 1
        b = 1
    return out

        
def LogModular(base, beta, n):
    for x in range(1,12):
        res = (base**x)%n
        if(res == beta):
            return x

#LogModular(2, 1, 11)
res = LogaritmerAvZ(board)
print(res)

[[10.  1.  8.  2.  4.  9.  7.  3.  6.  5.]
 [ 5. -1.  1.  4.  3. -1. -1. -1.  2. -1.]
 [ 5. -1.  4.  1.  2. -1. -1. -1.  3. -1.]
 [ 5. -1.  2.  3.  1. -1. -1. -1.  4. -1.]
 [10.  9.  2.  8.  6.  1.  3.  7.  4.  5.]
 [10.  3.  4.  6.  2.  7.  1.  9.  8.  5.]
 [10.  7.  6.  4.  8.  3.  9.  1.  2.  5.]
 [ 5. -1.  3.  2.  4. -1. -1. -1.  1. -1.]
 [ 2. -1. -1. -1. -1. -1. -1. -1. -1.  1.]]


#### 2.1)

In [34]:
def findFirstPrimitiveElement(arr, p):
    for i in range(len(arr)):
        if(arr[i][1] == p-1):
            return (arr[i][0], arr[i][1])
    
board, orders = findOrderOfZ(23)
result = findFirstPrimitiveElement(orders, 23)
print("Primitivt element i Z_41 er alpha={} med beta={}".format(result[0], result[1]))

Primitivt element i Z_41 er alpha=5 med beta=22


#### 2.2)

#### 2.3)

#### 2.4)

In [230]:
def FindNoOfPrimitiveElements(arr):
    n = len(arr)+1
    
    counter = 0
    for i in range(len(arr)):
        if(arr[i][1] == n-1):
            counter += 1
    return counter
            
    

board, orders = findOrderOfZ(41)

result = FindNoOfPrimitiveElements(orders)
print("Number of primitive elements is {}".format(result))

Number of primitive elements is 16


#### 3)

#### 4.1)

In [ ]:
n, e = (437, 13)
public_key = (n, e)

n,d = (437, 61)
private_key = (n,d)

alice_receive_1 = (78,394)
alice_receive_2 = (123,289)

def rsa_verify(m:tuple,public_key:tuple):
    x,y = m
    n, e = public_key
    res = rsa_encrypt(y,e,n)%n
    if(x == res):
        return "gyldig"
    else:
        return "ikke gyldig"
    
def rsa_encrypt(m:int, e:int, n:int):
    return (m**e)% n

def rsa_decrypt(cipher:int, d:int, n:int):
    return (cipher**d)% n

alice_verify = rsa_verify(alice_receive_1, public_key)
print("For (78, 394) så er signaturen", alice_verify)

alice_verify2 = rsa_verify(alice_receive_2, public_key)
print("For (123, 289) så er signaturen", alice_verify2)

#### 4.2)

#### 4.3)

#### 4.4)

In [ ]:
def rsa_sign(m:int, private_key:tuple):
    n, d = private_key
    res = rsa_decrypt(m,d, n)
    return (m, res)

def rsa_encrypt_signed(m:tuple, key:tuple):
    x,y = m
    n, e = key
    x1 =(x**e)% n
    y1 = (y**e)% n
    return (x1,y1)

def rsa_decrypt_signed(cipher:tuple, private_key:tuple):
    x, y = cipher
    n, d = private_key
    x1 = (x**d)%n
    y1 = (y**d)%n
    return (x1,y1)

#Signer først, så krypter.

#Alice stuff
n = 731
d = 19
e = 283
alice_public_key = (n,e)
alice_private_key = (n,d)

#bob stuff
n_bob = 437
e_bob = 13
d_bob = 61

bob_public_key = (n_bob, e_bob)
bob_private_key = (n_bob, d_bob)

m = 109

#Step 1: Sign
print("Before sign and encrypt=", m)
x,y = rsa_sign(m, alice_private_key)
print("After sign=", x,y)


#Step 2: Encrypt
encrypted = rsa_encrypt_signed((x,y), bob_public_key)
print("After encryption", encrypted)
print("Meldingen m={} blir til slutt {}".format(m,encrypted))

#Test to see if this is correct
decrypted = rsa_decrypt_signed(encrypted, bob_private_key)
print("\nTest correctness of sign and encrypt:")
print("Decrypted=",decrypted )
verify = rsa_verify(decrypted, alice_public_key)
print(verify)





#### 5.1)

Alice har satt opp ElGamal-signering basert på $13^{15}\bmod{37} = 29$  
   
Offentlig del av nøkkelen:  
p = 37  
alpha = 13  
beta = 29   
privat del av eksponenten er a = 15

#### 5.2)

Hun ønsker å signere meldingen 14 og 3 med henholdsvis   
k= 11 og k= 5.   

Hva blir signaturene?

In [103]:
def egcd(a, b):
    if a == 0:
        return (b, 0, 1)
    else:
        gcd, x, y = egcd(b % a, a)
        return (gcd, y - (b//a) * x, x)

def elGamalSign(message, k, p):
    n, alpha, a, beta = p
    
    __, x, _ = egcd(k, n-1)
    
    x = x%n-1
    y = pow(alpha,k,n)
    s =  ((message-a*y)*x)%(n-1)
    return (y, s)


public_key = (37, 13, 15, 29) # p(same as n), alpha, a, beta

m1 = 14
k1 = 11

res = elGamalSign(m1, k1, public_key)
print(res)

#print(elGamalEncrypt())

m2 = 3
k2 = 5

res2 = elGamalSign(m2, k2, public_key)
print(res2)

(15, 7)
(35, 18)


#### 5.3)

In [ ]:
def elGamalVerify(message, signature, p):
    n, alpha, a, beta = p
    r, s = signature

    if not((r >= 1) or (r <= (n-1))):
        return False

    v1 = ((beta**r)*(r**s))%n
    v2 = (alpha**message)%n
    
    print("V1=({}) vs V2=({})".format(v1,v2))
    return (v1 == v2)


message = 32
signature = (19,6)


verifiedMessage = elGamalVerify(message, signature, public_key)
print("Melding1 er ", verifiedMessage, "\n")


message2 = 9
signature2 = (32,16)

verifiedMessage2 = elGamalVerify(message2, signature2, public_key)
print("Melding2 er ", verifiedMessage2, "\n")


In [ ]:
import random
def elGamalEncrypt(message, keys, K_par=None):
    x = message
    p, alpha, a, beta = keys
    if(K_par == None):
        K = random.randint(0, 10)
    else:
        K = K_par
    
    alphaPowerK = (alpha**K)%p
    betaPowerK  = (beta**K)%p
    xTimesBetaPowerK = (x*betaPowerK)%p
    return (alphaPowerK, xTimesBetaPowerK)

Elgamal_key = (23, 5, 9, 11) # p(same as n), alpha, a, beta
encryptedElGamal = elGamalEncrypt(5, Elgamal_key, K_par=3)
print("Encrypted:",encryptedElGamal)


def elGamalDecrypt(cipher_tuple, keys):
    p, alpha, a, beta = keys
    first = (cipher_tuple[0]**a)%p
    _, x, __ = egcd(first, p)
    return (x*cipher_tuple[1])%p
    
decrypted = elGamalDecrypt(encryptedElGamal,Elgamal_key)
print("Decrypted:", decrypted)

In [107]:
def shanksAlgorithm2(p, alpha, beta):
    m = math.ceil(abs(math.sqrt(p)))
    
    x1 = (alpha**m)%p
    x2 = 0
    x2_list = []
    for j in range(0, m-1):
        x2 = (alpha**(m*j))%p
        print(x2)
        x2_list.append(x2)
    _, alphaInverse, __ = egcd(alpha, p)
    
    for i in range(0, m-1):
        betaTimesAlphaInversePowI = (beta*alphaInverse**i)%p
        if(betaTimesAlphaInversePowI in x2_list):
            indexOfJ = x2_list.index(betaTimesAlphaInversePowI)
            result = indexOfJ*alphaInverse+i
            return result

In [226]:
def shanksAlgorithm(p, alpha, beta):
    m = math.ceil(math.sqrt(p))
    
    l1 = []
    l2 = []
    
    for j in range(m):
        alpahPowerMJ = alpha**(m*j)%p
        l1.append((j, alpahPowerMJ))
        
    l1.sort(key=lambda tup: tup[1])
    
    alphaInverse = egcd(alpha, p)[1]
    for i in range(m):
        alphaPower = alphaInverse**i
        betaAlphaInverse = beta*alphaPower%p
        l2.append((i, betaAlphaInverse))
        
    l2.sort(key=lambda tup: tup[1])

    print("liste 1:",l1)
    print("liste 2:", l2)
    for x in range(len(l1)):
        for y in range(len(l2)):
            if(l1[x][1] == l2[y][1]):
                j = l1[x][0]
                i = l2[y][0]
                print("M=", m)
                print("i={}, j={}".format(i, j))
                res = (m*j+i)%p
                return res
    

In [227]:
p = 13
alpha= 2
beta = 11

res = shanksAlgorithm(p, alpha, beta)
print("Shanks algorithm found:", res)

liste 1: [(0, 1), (3, 1), (1, 3), (2, 9)]
liste 2: [(3, 3), (2, 6), (0, 11), (1, 12)]
M= 4
i=3, j=1
Shanks algorithm found: 7


In [ ]:
#EXAM 2020

p = 13
alpha = 2
beta = 11

resExam2020 = shanksAlgorithm(p, alpha, beta)
print(resExam2020)

In [13]:
def findAllCoprimes(n):
    arr = []
    for x in range(1,n):
        coprimeCheck = math.gcd(x, n)
        if(coprimeCheck == 1):
            arr.append(x)
            
    return arr

res = findAllCoprimes(26)
print(res)
print("29 har {} relativt primiske elementer".format(len(res)))


[1, 3, 5, 7, 9, 11, 15, 17, 19, 21, 23, 25]
29 har 12 relativt primiske elementer
