# Exercise 14

### Task 1

In [9]:
sumMod = (232 + 22 * 77 - 18*18) % 8
print(sumMod)

2


232 + 22 * 77 - 18^2 (mod 8)  
0 + 6 * 5 - 4 = 26 mod 8  
26 mod 8 = 2  


### Task 2

In [10]:
import numpy as np
import math

In [11]:
def multiplication_table_mod(MIN_MULTIPLIER, MAX_MULTIPLIER):
    # 2a
    matrix = np.zeros((MAX_MULTIPLIER-1, MAX_MULTIPLIER-1))

    for x in range(MIN_MULTIPLIER,MAX_MULTIPLIER):
        for y in range(MIN_MULTIPLIER,MAX_MULTIPLIER):
            matrix[x-1][y-1] = x*y%MAX_MULTIPLIER
    return matrix

def multiplicative_inverse(matrix):
    array = []
    for x in range(len(matrix)):
        for y in range(len(matrix)):
            if(matrix[x][y] == 1):
                array.append([x+1, y+1])
    return array

#### a)

In [12]:
multi_table_mod = multiplication_table_mod(1,12)
print(multi_table_mod)

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
 [ 2.  4.  6.  8. 10.  0.  2.  4.  6.  8. 10.]
 [ 3.  6.  9.  0.  3.  6.  9.  0.  3.  6.  9.]
 [ 4.  8.  0.  4.  8.  0.  4.  8.  0.  4.  8.]
 [ 5. 10.  3.  8.  1.  6. 11.  4.  9.  2.  7.]
 [ 6.  0.  6.  0.  6.  0.  6.  0.  6.  0.  6.]
 [ 7.  2.  9.  4. 11.  6.  1.  8.  3. 10.  5.]
 [ 8.  4.  0.  8.  4.  0.  8.  4.  0.  8.  4.]
 [ 9.  6.  3.  0.  9.  6.  3.  0.  9.  6.  3.]
 [10.  8.  6.  4.  2.  0. 10.  8.  6.  4.  2.]
 [11. 10.  9.  8.  7.  6.  5.  4.  3.  2.  1.]]


##### b)

In [13]:
multi_inverse = multiplicative_inverse(multi_table_mod)

for x in multi_inverse:
    print("{} * {} congruent 1 mod 12".format(x[0], x[1]))

1 * 1 congruent 1 mod 12
5 * 5 congruent 1 mod 12
7 * 7 congruent 1 mod 12
11 * 11 congruent 1 mod 12


In [14]:
print("\ntask c")


task c


### Task 3

In [15]:
def inverse_matrix(A):
    if np.linalg.det(A) != 0:
        return np.linalg.inv(A)*int(round(np.linalg.det(A)))
    else:
        return None 

def inverse_matrix_over_a(a, z):
    a_det = int(np.linalg.det(a))
    a_det_mod = a_det % len(z)
    z_multipl_inverse = multiplicative_inverse(z)

    det_in_multipl_inverse = False
    
    for x in z_multipl_inverse:
        if a_det_mod in x:
            det_in_multipl_inverse = True
    
    if(det_in_multipl_inverse):
        a_inv = inverse_matrix(a)
        return a_inv
    else:
        return None

#### a)

In [16]:
a = np.array([[2, -1], [5,8]])

z_10 = multiplication_table_mod(1,11)
inverse_over_z10 = inverse_matrix_over_a(a, z_10)
print("Invers over z10:")
print(inverse_over_z10)

Invers over z10:
[[ 8.  1.]
 [-5.  2.]]


#### b)

In [17]:
print("Invers over z9:")
z_9 = multiplication_table_mod(1,10)
inverse_over_z9 = inverse_matrix_over_a(a, z_9)
print(inverse_over_z9)

Invers over z9:
[[ 8.  1.]
 [-5.  2.]]


### Task 4

a)  
Et substitusjoncipher med alfabet med lengde 29 og med fast skift kan ha 29 forskjellige nøkler

b)  
Ved å endre på cipheret med fast lengde til et permutasjonscipher, så vil det eksistere 29! = 8,841761993739701e30 ulike nøkler.
Man kan også sette det opp i et blokkchifre, da har hver blokk en fast lengde, og bruker padding for å oppnå dette. Deretter så enkrypteres hver blokk med en forskjellig nøkkel.

c)  
Hvis vi lager et substitusjonschiffer for blokker med N-tegn, så har vi alfabetet = 29^n

### Task 5

In [18]:
def alphabet_list():
    letters = []
    for x in range(26):
        letters.append(chr(65+x))
        
    letters.append('Æ')
    letters.append('Ø')
    letters.append('Å')
    return letters

def k_shift_cipher_decode(cipher, shift):
    trimmedCipher = cipher.replace(" ", "").upper()
    
    letters = alphabet_list()

    decoded_string = ""
    for letter in trimmedCipher:
        index = (letters.index(letter) + shift) % len(letters)
        decoded_string += letters[index]
    return decoded_string

print("Dekodet cipher er:")
decoded_string = k_shift_cipher_decode("YÆVFB VBVFR ÅVBV", 12)
print(decoded_string)

Dekodet cipher er:
HJERNENERALENE


### Task 6

### Task 7   - Vigenere chiffer

#### A)

In [19]:
def create_vigenere_table():
    table = np.zeros((29,29), 'U1')

    letters = [chr(65+x) for x in range(26)]
    letters.append('Æ')
    letters.append('Ø')
    letters.append('Å')

    for row in range(len(letters)):
        for col in range(len(letters)):
            charToAdd = (col+row) % len(letters)
            table[row][col] = letters[charToAdd]
            
    return (table, letters)

def encrypt(cleartext, key):
    table, letters = create_vigenere_table()
    cipher = ""

    for i, letter in enumerate(cleartext):
        indexCol = letters.index(letter)
        indexRow = letters.index(key[i % len(key)])
        cipher += table[indexRow][indexCol]
    return cipher

def decrypt(cipher, key):
    table, letters = create_vigenere_table()
    cleartext = ""

    for i, letter in enumerate(cipher):
        indexCol = letters.index(letter)
        indexRow = letters.index(key[i % len(key)])
        cleartext += letters[(indexCol - indexRow) % len(letters)]
    return cleartext
    
cleartext = "Nå er det snart helg".replace(" ", "").upper()
key = "torsk".upper()


cipher = encrypt(cleartext, key)
print("Encrypted cipher: ", cipher)

decrypted = decrypt(cipher, key)
print("Decrypted cleartext:", decrypted)
    


Encrypted cipher:  DNVGNXEGCKHEYWVZ
Decrypted cleartext: NÅERDETSNARTHELG


#### B)

In [20]:
cipher_b = "QZQOBVCAFFKSDC"
key_b = "BRUS"
decrypted_b = decrypt(cipher_b, key_b)
print("Dekrypter tekst er=",decrypted_b)

Dekrypter tekst er= PIZZAELLERTACO


#### C)

### Task 8

#### A)

In [21]:
K = np.array([[11, 8], [3, 7]])
z_29 = multiplication_table_mod(1,29)
K_inv = inverse_matrix_over_a(K, z_29)
print("K invers over z_29:")
print(K_inv)

K invers over z_29:
[[ 7. -8.]
 [-3. 11.]]


#### B)

In [22]:
def egcd(a, b):
    if a == 0:
        return (b, 0, 1)
    else:
        gcd, x, y = egcd(b % a, a)
        return (gcd, y - (b//a) * x, x)

def vectorize_string(text):
    vector = []
    for letter in text:
        indexLetter = letters.index(letter)
        vector.append(indexLetter)
    vector = np.array(vector)
    return vector

def encrypt_hill(cleartext, k_matrix):
    if(len(cleartext)%2 == 0):
        cleartext_vector = vectorize_string(cleartext).reshape((-1,2))
    else:
        cleartext_vector = vectorize_string(cleartext+"A").reshape((-1,2))
    cipher = ""
    
    print("Key:")
    print(k_matrix)
    print("\n")
    
    print("Cleartext vector:")
    print(cleartext_vector)
    print("\n")
    
    e_list = []
    print("Encryption:")
    for vector in cleartext_vector:
        encryption = (k_matrix@vector)%len(letters)
  
        print(encryption)
        e_list.append(encryption)
    print("\n")
    for row in e_list:
        for column in row:
            cipher += letters[column%len(letters)]
            
    return cipher

def decrypt_hill(cipher, K):
    K_inv = inverse_matrix(K)
    if(len(cipher)%2 == 0):
        cipher_vector = vectorize_string(cipher).reshape((-1,2))
    else:
        cipher_vector = vectorize_string(cipher+"A").reshape((-1,2))
        
    print("Key inverse:")
    print(K)
    print("\n")

    detK = int(round(np.linalg.det(K)))
    detKInv = egcd(detK, 29)[1]%29
    print(detKInv)

    print("Cipher vector:")
    print(cipher_vector)
    print("\n")
    
    d_list = []
    print("Decrypted text:")
    for vector in cipher_vector:
        decryption = (detKInv*K_inv@vector)% len(letters)
        print(decryption)
        d_list.append(decryption)

    print("\n")
    cleartext = ""
    for row in d_list:
        for column in row:
            cleartext += letters[int(math.ceil(column))%len(letters)]
    return cleartext

In [23]:
letters = alphabet_list()

cleartext_hill= "prim".upper()
cipher_hill_text = encrypt_hill(cleartext_hill, K)
print("Encrypted cipher is:", cipher_hill_text)

#Testing with decrypt
decryptHillText = decrypt_hill(cipher_hill_text, K)
print("Decrypted text is:", decryptHillText)

Key:
[[11  8]
 [ 3  7]]


Cleartext vector:
[[15 17]
 [ 8 12]]


Encryption:
[11 19]
[10 21]


Encrypted cipher is: LTKV
Key inverse:
[[11  8]
 [ 3  7]]


23
Cipher vector:
[[11 19]
 [10 21]]


Decrypted text:
[15. 17.]
[ 8. 12.]


Decrypted text is: PRIM


In [24]:
cipher = "TOYYSN"
cleartext_c = decrypt_hill(cipher, K)
print(cleartext_c)

Key inverse:
[[11  8]
 [ 3  7]]


23
Cipher vector:
[[19 14]
 [24 24]
 [18 13]]


Decrypted text:
[19. 27.]
[28.  8.]
[13. 17.]


TØÅINR


#### D)

In [25]:
actual_cleartext = "EASY"
actual_cipher = "IØÅY"
m=2

#now crack this
test_crack = decrypt_hill(actual_cipher, K_inv)
'''


while actual_cleartext is not test_crack:
    for x in range(1,100):
        new_K = multiplication_table_mod(1,x)
        new_K_inv = inverse_matrix(new_K)
        try:
            pass
            #test_crack = decrypt_hill(actual_cipher, new_K)
        except:
            pass

print(test_crack)
'''

Key inverse:
[[ 7. -8.]
 [-3. 11.]]


23
Cipher vector:
[[ 8 27]
 [28 24]]


Decrypted text:
[ 3. 27.]
[16. 25.]




'\n\n\nwhile actual_cleartext is not test_crack:\n    for x in range(1,100):\n        new_K = multiplication_table_mod(1,x)\n        new_K_inv = inverse_matrix(new_K)\n        try:\n            pass\n            #test_crack = decrypt_hill(actual_cipher, new_K)\n        except:\n            pass\n\nprint(test_crack)\n'

In [39]:
def affine_encrypt(message, key, n):
    a, b = key
    cipher_list = []
    for x in message:
        e = (a*x+b)%n
        cipher_list.append(e)
    return cipher_list
    
def affine_decrypt(cipher, key, n):
    a, b = key
    _, aInv, __= egcd(a, n)
    plaintext = []
    for x in cipher:
        p = (aInv*(x-b))%n
        plaintext.append(p)
    return plaintext

message = [20]
key = (15, 3)
encrypted = affine_encrypt(message, key, 26)
print("Cipher is:", encrypted)


deciphered = affine_decrypt(encrypted, key, 26)
print("Deciphered plaintext is:", deciphered)

cipher2 = [ 25, 11, 13]
deciphered2 = affine_decrypt(cipher2, key, 26)
print("EXAM DECIPHER IS:", deciphered2)

Cipher is: [17]
Deciphered plaintext is: [20]
EXAM DECIPHER IS: [24, 4, 18]
